apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-redis-app
  template:
    metadata:
      labels:
        app: flask-redis-app
    spec:
      containers:
        - name: flask-app
          image: vishwacloudlab/pythonapp:v4-var
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis-service"   # Kubernetes Service name for Redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: APP_PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-redis-service
spec:
  type: NodePort
  selector:
    app: flask-redis-app
  ports:
    - port: 80
      targetPort: 8000
